import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <div className="min-h-screen flex-col items-center justify-between py-20 px-5">
          {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  )
}
